<a href="https://colab.research.google.com/github/Seanzhengocean1/DS_Week6/blob/main/_Day_27_06072023_A_excerciese_in_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Day 27 06072023 A-excerciese in class

import pandas as pd 
import numpy as np

df_dataset_m=pd.read_csv('/content/preprocessingcsv.csv')
df_dataset_m

X=df_dataset_m.iloc[:,:-1].values #independent
y=df_dataset_m.iloc[:,-1].values #dependent


from sklearn.compose import ColumnTransformer # sklearn.compose.ColumnTransformer
from sklearn.preprocessing import OneHotEncoder # sklearn.preprocessing.OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

from sklearn.model_selection import train_test_split
# sklearn.model_selection.train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# X_train, X_test, y_train, y_test 


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

X_train,X_test

[[1.0 0.0 1.0 0.0 1850 2 5 2]
 [0.0 1.0 0.0 1.0 1600 2 10 2]
 [1.0 0.0 1.0 0.0 1500 2 15 3]
 [0.0 1.0 0.0 1.0 2000 2 3 2]
 [1.0 0.0 0.0 1.0 2000 3 2 4]
 [0.0 1.0 0.0 1.0 2500 3 4 2]
 [1.0 0.0 0.0 1.0 2500 3 5 3]
 [0.0 1.0 0.0 1.0 2500 4 6 3]
 [1.0 0.0 0.0 1.0 3000 4 7 4]
 [0.0 1.0 0.0 1.0 3000 4 8 2]
 [1.0 0.0 0.0 1.0 3200 4 10 4]
 [0.0 1.0 0.0 1.0 3200 5 9 2]
 [1.0 0.0 0.0 1.0 4000 5 8 5]
 [0.0 1.0 0.0 1.0 4500 5 10 4]]


(array([[0.0, 1.0, 0.0, 0.47140452079103157, 0.5244467974701875,
         1.2532566273166255, 0.30794088102571987, -0.7954951288348661],
        [1.0, 0.0, 1.0, -2.121320343559643, -1.3086663077059812,
         -1.179535649239177, 2.155586167180039, 0.1767766952966367],
        [0.0, 1.0, 0.0, 0.47140452079103157, 1.9262391720166694,
         1.2532566273166255, 0.6158817620514397, 1.1490485194281395],
        [0.0, 1.0, 0.0, 0.47140452079103157, 0.30878643215534407,
         0.44232586846469135, 0.0, -0.7954951288348661],
        [0.0, 1.0, 0.0, 0.47140452079103157, -1.2008361250485597,
         -1.179535649239177, 0.6158817620514397, -0.7954951288348661],
        [0.0, 1.0, 0.0, 0.47140452079103157, -0.2303644811317644,
         0.44232586846469135, -0.6158817620514397, 0.1767766952966367],
        [1.0, 0.0, 0.0, 0.47140452079103157, 0.5244467974701875,
         0.44232586846469135, 0.6158817620514397, 1.1490485194281395],
        [0.0, 1.0, 0.0, 0.47140452079103157, -0.769515394418