<a href="https://colab.research.google.com/github/Seanzhengocean1/DS_Week5/blob/main/Day22_A_05312023_01JUN2023_DS_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
!pip install matplotlib

In [ ]:
!pip install sklearn # scikit-learn

In [ ]:
import numpy as np

In [ ]:
lst1 = [1,2,3,4,5,6,7,8,9,10]
arr1 = np.array(lst1)
print(arr1)
print(type(arr1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
tup1 = ['p1','o2','i3','u4','y5','t6','r7','e8','w9','q10']
arr2 = np.array(tup1)
print(arr2)
print(type(arr2))

['p1' 'o2' 'i3' 'u4' 'y5' 't6' 'r7' 'e8' 'w9' 'q10']
<class 'numpy.ndarray'>


In [ ]:
set1 = {'p1','o2','i3','u4','y5','t6','r7','e8','w9','q10',True,False,1,2,3,4,5,6,7,8,9,10}
arr3 = np.array(set1)
print(arr3)
print(type(arr3))

{'q10', True, 2, False, 'p1', 3, 4, 5, 6, 7, 'w9', 8, 9, 10, 'i3', 'r7', 'y5', 'e8', 'u4', 'o2', 't6'}
<class 'numpy.ndarray'>


In [ ]:
dict1 = {'p1':1,'o2':2,'i3':3,'u4':4,'y5':5,'t6':6,'r7':7,'e8':8,'w9':9,'q10':10}
arr4 = np.array(dict1)
print(arr4)
print(type(arr4))

{'p1': 1, 'o2': 2, 'i3': 3, 'u4': 4, 'y5': 5, 't6': 6, 'r7': 7, 'e8': 8, 'w9': 9, 'q10': 10}
<class 'numpy.ndarray'>


In [ ]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)
print(type(arr5))

Python Programming
<class 'numpy.ndarray'>


In [ ]:
lst1 = [10,20,30,40,50,60,70,80,90,100]
arr1 = np.array(lst1)
print(arr1)
print(type(arr1))
arr1

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.astype(float)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(100,0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [ ]:
arr7 = np.arange(100,0, -10)
arr7, arr7.dtype, arr7.shape

(array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10]),
 dtype('int64'),
 (10,))

In [ ]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]]
arr7_2d = np.array(lst2)
print(arr7_2d)
print(type(arr7_2d))
arr7_2d.dtype, arr7_2d.size, arr7_2d.ndim, arr7_2d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


(dtype('int64'), 9, 2, (3, 3))

In [ ]:
lst3 = [
        [
            [1,2,3],[2,3,4],[3,4,5]
         ],
          [
              [4,5,6],[5,6,7],[6,7,8]
           ],
            [
                [7,8,9],[8,9,0],[9,0,1]
             ]
        ]

In [ ]:
arr8_3d = np.array(lst3)

In [ ]:
arr8_3d

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]],

       [[7, 8, 9],
        [8, 9, 0],
        [9, 0, 1]]])

In [ ]:
arr8_3d.ndim

3

In [ ]:
arr8_3d.shape

(3, 3, 3)

In [ ]:
np.random.random(10)

array([0.56944356, 0.86078123, 0.80927569, 0.1434573 , 0.33913777,
       0.19072474, 0.86748173, 0.58593626, 0.38710305, 0.53477577])

In [ ]:
np.random.random(1000)

array([0.50871606, 0.18107894, 0.84539725, 0.27554686, 0.30680953,
       0.39425966, 0.06268987, 0.62527045, 0.22542846, 0.23186221,
       0.08841827, 0.82938282, 0.72041118, 0.43478605, 0.17160464,
       0.77450954, 0.90197537, 0.0785062 , 0.86205177, 0.83425998,
       0.55635567, 0.21107816, 0.91049241, 0.87359608, 0.43327202,
       0.56235635, 0.36679615, 0.81683598, 0.65624803, 0.40289377,
       0.78798175, 0.78414735, 0.32162488, 0.33403301, 0.63804608,
       0.26916514, 0.91630661, 0.71279423, 0.66827098, 0.41039442,
       0.98439159, 0.3771949 , 0.20478956, 0.23950164, 0.3151928 ,
       0.65762042, 0.02916373, 0.91571897, 0.32164995, 0.60025274,
       0.0472769 , 0.46360067, 0.987022  , 0.0065563 , 0.24655705,
       0.70283106, 0.20082254, 0.65565819, 0.31534357, 0.4614863 ,
       0.79832918, 0.35344072, 0.68882182, 0.38434864, 0.75051451,
       0.71101709, 0.59710788, 0.86120747, 0.23014375, 0.96430529,
       0.59531783, 0.3922354 , 0.22379565, 0.56878044, 0.00305

In [ ]:
np.random.randint(0, 500, 5)

array([406, 373, 208, 365,  58])

In [ ]:
np.random.randint(-1000, -500, 5)

array([-859, -877, -728, -941, -585])

In [ ]:
np.random.randint(-500, -1,  25)

array([-405, -139, -491,  -40, -380, -125, -301, -151, -247, -351, -142,
       -397, -274, -335, -459, -272, -293, -454, -434,  -90,  -35, -289,
       -333, -458, -482])