In [38]:
import numpy as np
import pandas as pd


In [39]:
df=pd.read_csv("/content/preprocessing_sabin.xlsx - Sheet1.csv")
df

area  no_bhk  age locality  parking facilities   rent
0   1850       2    5    rural        2          N   8000
1   1600       2   10    urban        2          Y  15000
2   1500       2   15    rural        3          N   9000
3   2000       2    3    urban        2          Y  16000
4   2000       3    2    rural        4          Y  12000
5   2500       3    4    urban        2          Y  15000
6   2500       3    5    rural        3          Y  12000
7   2500       4    6    urban        3          Y  18000
8   3000       4    7    rural        4          Y  15000
9   3000       4    8    urban        2          Y  20000
10  3200       4   10    rural        4          Y  14000
11  3200       5    9    urban        2          Y  23000
12  4000       5    8    rural        5          Y  19000
13  4500       5   10    urban        4          Y  28000

In [40]:
X = df.iloc[:,:-1].values #independent
y = df.iloc[:,-1].values #dependent

# ***catogorical data***

In [42]:
from sklearn.compose import ColumnTransformer # sklearn.compose.ColumnTransformer
from sklearn.preprocessing import OneHotEncoder # sklearn.preprocessing.OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 1850 5 2]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1600 10 2]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 1500 15 3]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 2000 3 2]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 2000 2 4]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 2500 4 2]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 2500 5 3]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 2500 6 3]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 3000 7 4]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 3000 8 2]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 3200 10 4]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 3200 9 2]
 [0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 4000 8 5]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 4500 10 4]]


# ***Splitting dataset into training and test***

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train, X_test, y_train, y_test 

(array([[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1500, 15, 3],
        [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 3200, 10, 4],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2000, 2, 4],
        [0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1600, 10, 2],
        [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 4000, 8, 5],
        [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1850, 5, 2],
        [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 4500, 10, 4],
        [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3000, 8, 2],
        [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 3000, 7, 4],
        [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 3200, 9, 2],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2500, 4, 2]],
       dtype=object),
 array([[0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2000, 3, 2],
        [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 2500, 6, 3],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2500, 5, 3]],
       dtype=object),
 array([ 900

# ***Feature Scaling(-3 to-2)(pick the table with different units and numeric one***

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,4:] = sc.fit_transform(X_train[:,4:])
X_test[:,4:] = sc.transform(X_test[:,4:])

In [50]:
X_train, X_test

(array([[1.0, 0.0, 1.0, 0.0, -0.6123724356957946, -0.6123724356957946,
         0.9128709291752769, -0.9128709291752769, 2.1213203435596433,
         -1.3567025990020243, 2.0848918901344473, -0.08391813582966888],
        [0.0, 1.0, 0.0, 0.0, 1.6329931618554523, -0.6123724356957946,
         0.9128709291752769, -0.9128709291752769, -0.4714045207910318,
         0.47509080181659336, 0.5956833971812706, 0.8391813582966892],
        [0.0, 1.0, 0.0, 1.0, -0.6123724356957946, -0.6123724356957946,
         0.9128709291752769, -0.9128709291752769, -0.4714045207910318,
         -0.8179398340553721, -1.7870501915438122, 0.8391813582966892],
        [0.0, 1.0, 1.0, 0.0, -0.6123724356957946, -0.6123724356957946,
         -1.0954451150103324, 1.0954451150103324, -0.4714045207910318,
         -1.2489500460126939, 0.5956833971812706, -1.007017629956027],
        [0.0, 1.0, 0.0, 0.0, -0.6123724356957946, 1.6329931618554523,
         0.9128709291752769, -0.9128709291752769, -0.4714045207910318,
      